# By Harsh H. Rajpurohit
name: safe_vpn
description: "A new Flutter project."
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.6.5

  # Cupertino style icons
  cupertino_icons: ^1.0.2

  # For API Call
  http: ^1.0.0

  # Converting CSV data to List
  csv: ^5.0.2

  # For Lottie Animation
  lottie: ^2.3.2

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^3.0.0

  # For firebase
  firebase_core: ^2.14.0

  # For Remote Config
  firebase_remote_config: ^4.2.3
  rename: ^3.0.2
  flutter_file_dialog: ^3.0.2
  url_launcher: ^6.2.6
  share_plus: ^7.2.2
  # flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/